# Which employees have the highest salary in the pharmacy store?

select name,salary from Employee where salary = (select max(salary) from Employee);

# What is the average salary of employees in different roles (e.g., Pharmacists, Doctors, Salespersons)?

select role,round(avg(salary),2) from Employee group by role;

# Which medicines are the top-selling in terms of total sales?

select m.name, sum(s.quantity) as total_medicine_quantity, sum(s.total_price) as total_medicine_revenue from Sales s join Medicine m on m.medicine_id = s.medicine_id group by m.name order by total_medicine_revenue desc limit 5;

# What is the total sales revenue generated in a particular month (e.g., January 2025)?

select sum(total_price) as total_revenue from Sales where month(salestime) = 4 and year(salestime) = 2025;

# How many sales were made by each employee in a given month?

select e.name, count(s.sales_id) as sales_count from Employee e join Sales s on e.employee_id = s.employee_id where month(s.salestime) = 4 and year(salestime) = 2025 group by e.name;

# Which customers have made the most purchases in terms of total spent?

select c.name, sum(s.total_price) as total_spent from Customer c join Sales s on c.customer_id = s.customer_id group by c.name order by total_spent desc limit 5;

# How many consultations have been made by each customer?

select c.name, count(co.consultation_id) as total_consultation from Consultation co join Customer c on co.customer_id = c.customer_id group by c.customer_id;

# Which doctors have the highest consultation fees?

select name, consultation_fee from Doctor where consultation_fee = (select max(consultation_fee) from Doctor);

# How many consultations were conducted by each doctor?

select d.name, count(co.consultation_id) as total_consultation from Doctor d join Consultation co on d.doctor_id = co.doctor_id group by d.doctor_id;

# Which medicines are about to expire within the next 30 days?

select name, expiry_date from Medicine WHERE expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY);

# What is the total quantity of each medicine available in the store?

select name, quantity from Medicine group by medicine_id;

# What are the most prescribed medicines in the pharmacy?

select m.name, count(p.medicine_id) as prescription_count from Medicine m join Prescription p on m.medicine_id = p.medicine_id group by m.medicine_id order by prescription_count desc limit 5;

# Which customer has received the most prescriptions?

select c.name, count(p.customer_id) as prescription_count from Customer c join Prescription p on c.customer_id = p.customer_id group by c.customer_id order by prescription_count desc limit 5;

# How much revenue has been generated from a particular doctor’s consultations in the past month?

select d.name, sum(c.fee_paid) as revenue from consultation c join doctor d on c.doctor_id = d.doctor_id where c.doctor_id = 1 and month(c.consultation_date) = 4 and year(c.consultation_date) = 2025;

# What is the total revenue generated by the pharmacy from both sales and consultations in the last month?

select (sum(c.fee_paid) + sum(s.total_price)) as total_revenue from consultation c join sales s on month(c.consultation_date) = month(s.salestime) and year(c.consultation_date) = year(s.salestime) where month(s.salestime) = 4 and year(s.salestime) = 2025;

# What is the average amount spent by customers per transaction in pharmacy?

select avg(total_price) as average_amount from sales;

# Which medicine is being purchased most frequently by regular customers (who make more than 5 purchases)?

select m.name, count(s.sales_id) as purchase_count from medicine m join sales s on m.medicine_id = s.medicine_id join customer c on s.customer_id = c.customer_id group by m.name having count(s.sales_id)>3 order by purchase_count desc;

# Which medicines have the highest stock value based on their quantity and price?

select name, category, brand, (price * quantity) as stock_value from medicine order by stock_value desc;

# How many medicines are nearing their expiry date (within 60 days) from each supplier?

select s.name, count(m.medicine_id) from Medicine m join Supplier s on m.supplier_id = s.supplier_id where m.expiry_date between curdate() and date_add(curdate(), interval 60 day) group by m.supplier_id;

# How many different medicines are provided by each supplier?

select s.name, count(m.medicine_id) from Medicine m join Supplier s on m.supplier_id = s.supplier_id group by s.supplier_id;

# What is the total consultation revenue generated by each doctor in the last 30 days?

select d.name, sum(c.fee_paid) as consultation_revenue from Doctor d join Consultation c on d.doctor_id = c.doctor_id where c.consultation_date between date_sub(curdate(), interval 30 day) and curdate() group by d.doctor_id;

# How many consultations did each doctor conduct on weekends (Saturday and Sunday)?

select d.name, COUNT(c.consultation_id) as weekend_consultations from Consultation c join Doctor d on c.doctor_id = d.doctor_id where DAYOFWEEK(c.consultation_date) in (1, 7) group by d.name;

# Which doctor has the highest number of consultations in the last 6 months?

select d.name, count(c.consultation_id) as consultations from Consultation c join Doctor d on c.doctor_id = d.doctor_id where c.consultation_date between date_sub(curdate(), interval 60 day) and curdate() group by d.name order by consultations desc;

# How many prescriptions have been written for each customer?

select c.name, count(p.prescription_id) as total_prescription from Customer c join Prescription p on c.customer_id = p.customer_id group by c.customer_id;

# What are the most prescribed combinations of medicines (medicine pairs) in prescriptions?
# Which medicines have a low stock (below a certain threshold, e.g., 10 units)?

select name, quantity from Medicine where quantity < 200;

# What is the total quantity of each medicine sold over a specified period (e.g., last 3 months)?

select m.name, count(s.quantity) as sold_quantity from Medicine m join Sales s on m.medicine_id = s.medicine_id where s.salestime between date_sub(curdate(), interval 30 day) and curdate() group by m.medicine_id;

# What is the total revenue generated from both sales and consultations each day?

select date(s.salestime) as date, (sum(s.total_price)+sum(c.fee_paid)) from Sales s join Consultation c on date(s.salestime) = date(c.consultation_date) group by date;

# What is the average revenue per employee for the last 6 months?

select e.name, sum(s.total_price) / count(distinct(s.sales_id)) as avg_revenue from Employee e join Sales s on e.employee_id = s.employee_id where s.salestime between date_sub(curdate(), interval 180 day) and curdate() group by e.employee_id order by avg_revenue desc ;

# Which doctors have consulted the highest number of customers in the past month?

select d.name, max(c.consultation_id) as consultation_count from Doctor d join Consultation c on d.doctor_id = c.doctor_id group by d.doctor_id order by consultation_count desc;
